package com.builders.wallet.samsungpay.util

import com.samsung.android.sdk.samsungpay.v2.SpaySdk

object ErrorCode {
    fun getErrorCodeName(errorCode: Int): String {
        return when (errorCode) {
            SpaySdk.ERROR_NONE -> "ERROR_NONE"
            SpaySdk.ERROR_SPAY_INTERNAL -> "ERROR_SPAY_INTERNAL"
            SpaySdk.ERROR_INVALID_INPUT -> "ERROR_INVALID_INPUT"
            SpaySdk.ERROR_NOT_SUPPORTED -> "ERROR_NOT_SUPPORTED"
            SpaySdk.ERROR_NOT_FOUND -> "ERROR_NOT_FOUND"
            SpaySdk.ERROR_ALREADY_DONE -> "ERROR_ALREADY_DONE"
            SpaySdk.ERROR_NOT_ALLOWED -> "ERROR_NOT_ALLOWED"
            SpaySdk.ERROR_USER_CANCELED -> "ERROR_USER_CANCELED"
            SpaySdk.ERROR_PARTNER_SDK_API_LEVEL -> "ERROR_PARTNER_SDK_API_LEVEL"
            SpaySdk.ERROR_PARTNER_SERVICE_TYPE -> "ERROR_PARTNER_SERVICE_TYPE"
            SpaySdk.ERROR_INVALID_PARAMETER -> "ERROR_INVALID_PARAMETER"
            SpaySdk.ERROR_NO_NETWORK -> "ERROR_NO_NETWORK"
            SpaySdk.ERROR_SERVER_NO_RESPONSE -> "ERROR_SERVER_NO_RESPONSE"
            SpaySdk.ERROR_PARTNER_INFO_INVALID -> "ERROR_PARTNER_INFO_INVALID"
            SpaySdk.ERROR_INITIATION_FAIL -> "ERROR_INITIATION_FAIL"
            SpaySdk.ERROR_REGISTRATION_FAIL -> "ERROR_REGISTRATION_FAIL"
            SpaySdk.ERROR_DUPLICATED_SDK_API_CALLED -> "ERROR_DUPLICATED_SDK_API_CALLED"
            SpaySdk.ERROR_SDK_NOT_SUPPORTED_FOR_THIS_REGION -> "ERROR_SDK_NOT_SUPPORTED_FOR_THIS_REGION"
            SpaySdk.ERROR_SERVICE_ID_INVALID -> "ERROR_SERVICE_ID_INVALID"
            SpaySdk.ERROR_SERVICE_UNAVAILABLE_FOR_THIS_REGION -> "ERROR_SERVICE_UNAVAILABLE_FOR_THIS_REGION"
            SpaySdk.ERROR_PARTNER_APP_SIGNATURE_MISMATCH -> "ERROR_PARTNER_APP_SIGNATURE_MISMATCH"
            SpaySdk.ERROR_PARTNER_APP_VERSION_NOT_SUPPORTED -> "ERROR_PARTNER_APP_VERSION_NOT_SUPPORTED"
            SpaySdk.ERROR_PARTNER_APP_BLOCKED -> "ERROR_PARTNER_APP_BLOCKED"
            SpaySdk.ERROR_USER_NOT_REGISTERED_FOR_DEBUG -> "ERROR_USER_NOT_REGISTERED_FOR_DEBUG"
            SpaySdk.ERROR_SERVICE_NOT_APPROVED_FOR_RELEASE -> "ERROR_SERVICE_NOT_APPROVED_FOR_RELEASE"
            SpaySdk.ERROR_PARTNER_NOT_APPROVED -> "ERROR_PARTNER_NOT_APPROVED"
            SpaySdk.ERROR_UNAUTHORIZED_REQUEST_TYPE -> "ERROR_UNAUTHORIZED_REQUEST_TYPE"
            SpaySdk.ERROR_EXPIRED_OR_INVALID_DEBUG_KEY -> "ERROR_EXPIRED_OR_INVALID_DEBUG_KEY"
            SpaySdk.ERROR_SERVER_INTERNAL -> "ERROR_SERVER_INTERNAL"
            SpaySdk.ERROR_DEVICE_NOT_SAMSUNG -> "ERROR_DEVICE_NOT_SAMSUNG"
            SpaySdk.ERROR_SPAY_PKG_NOT_FOUND -> "ERROR_SPAY_PKG_NOT_FOUND"
            SpaySdk.ERROR_SPAY_SDK_SERVICE_NOT_AVAILABLE -> "ERROR_SPAY_SDK_SERVICE_NOT_AVAILABLE"
            SpaySdk.ERROR_DEVICE_INTEGRITY_CHECK_FAIL -> "ERROR_DEVICE_INTEGRITY_CHECK_FAIL"
            SpaySdk.ERROR_SPAY_APP_INTEGRITY_CHECK_FAIL -> "ERROR_SPAY_APP_INTEGRITY_CHECK_FAIL"
            SpaySdk.ERROR_ANDROID_PLATFORM_CHECK_FAIL -> "ERROR_ANDROID_PLATFORM_CHECK_FAIL"
            SpaySdk.ERROR_MISSING_INFORMATION -> "ERROR_MISSING_INFORMATION"
            SpaySdk.ERROR_SPAY_SETUP_NOT_COMPLETED -> "ERROR_SPAY_SETUP_NOT_COMPLETED"
            SpaySdk.ERROR_SPAY_APP_NEED_TO_UPDATE -> "ERROR_SPAY_APP_NEED_TO_UPDATE"
            SpaySdk.ERROR_PARTNER_SDK_VERSION_NOT_ALLOWED -> "ERROR_PARTNER_SDK_VERSION_NOT_ALLOWED"
            SpaySdk.ERROR_UNABLE_TO_VERIFY_CALLER -> "ERROR_UNABLE_TO_VERIFY_CALLER"
            SpaySdk.ERROR_SPAY_FMM_LOCK -> "ERROR_SPAY_FMM_LOCK"
            SpaySdk.ERROR_SPAY_CONNECTED_WITH_EXTERNAL_DISPLAY -> "ERROR_SPAY_CONNECTED_WITH_EXTERNAL_DISPLAY"
            SpaySdk.SPAY_NOT_SUPPORTED -> "SPAY_NOT_SUPPORTED"
            SpaySdk.SPAY_NOT_READY -> "SPAY_NOT_READY"
            SpaySdk.SPAY_READY -> "SPAY_READY"
            SpaySdk.SPAY_NOT_ALLOWED_TEMPORALLY -> "SPAY_NOT_ALLOWED_TEMPORALLY"
            SpaySdk.SPAY_HAS_TRANSIT_CARD -> "SPAY_HAS_TRANSIT_CARD"
            SpaySdk.SPAY_HAS_NO_TRANSIT_CARD -> "SPAY_HAS_NO_TRANSIT_CARD"
            else -> "UNKNOWN_ERROR_$errorCode"
        }
    }

    fun getErrorMessage(errorCode: Int): String {
        return when (errorCode) {
            SpaySdk.ERROR_NONE -> "Nenhum erro"
            SpaySdk.ERROR_SPAY_INTERNAL -> "Erro interno do Samsung Pay"
            SpaySdk.ERROR_INVALID_INPUT -> "Entrada inválida"
            SpaySdk.ERROR_NOT_SUPPORTED -> "Não suportado"
            SpaySdk.ERROR_NOT_FOUND -> "Não encontrado"
            SpaySdk.ERROR_ALREADY_DONE -> "Já foi executado"
            SpaySdk.ERROR_NOT_ALLOWED -> "Não permitido"
            SpaySdk.ERROR_USER_CANCELED -> "Cancelado pelo usuário"
            SpaySdk.ERROR_PARTNER_SDK_API_LEVEL -> "Nível de API do parceiro inválido"
            SpaySdk.ERROR_PARTNER_SERVICE_TYPE -> "Tipo de serviço do parceiro inválido"
            SpaySdk.ERROR_INVALID_PARAMETER -> "Parâmetro inválido"
            SpaySdk.ERROR_NO_NETWORK -> "Sem conexão de rede"
            SpaySdk.ERROR_SERVER_NO_RESPONSE -> "Servidor sem resposta"
            SpaySdk.ERROR_PARTNER_INFO_INVALID -> "Informações do parceiro inválidas"
            SpaySdk.ERROR_INITIATION_FAIL -> "Falha na inicialização"
            SpaySdk.ERROR_REGISTRATION_FAIL -> "Falha no registro"
            SpaySdk.ERROR_DUPLICATED_SDK_API_CALLED -> "API do SDK chamada duplicada"
            SpaySdk.ERROR_SDK_NOT_SUPPORTED_FOR_THIS_REGION -> "SDK não suportado para esta região"
            SpaySdk.ERROR_SERVICE_ID_INVALID -> "ID do serviço inválido"
            SpaySdk.ERROR_SERVICE_UNAVAILABLE_FOR_THIS_REGION -> "Serviço indisponível para esta região"
            SpaySdk.ERROR_PARTNER_APP_SIGNATURE_MISMATCH -> "Assinatura do app parceiro não confere"
            SpaySdk.ERROR_PARTNER_APP_VERSION_NOT_SUPPORTED -> "Versão do app parceiro não suportada"
            SpaySdk.ERROR_PARTNER_APP_BLOCKED -> "App parceiro bloqueado"
            SpaySdk.ERROR_USER_NOT_REGISTERED_FOR_DEBUG -> "Usuário não registrado para debug"
            SpaySdk.ERROR_SERVICE_NOT_APPROVED_FOR_RELEASE -> "Serviço não aprovado para release"
            SpaySdk.ERROR_PARTNER_NOT_APPROVED -> "Parceiro não aprovado"
            SpaySdk.ERROR_UNAUTHORIZED_REQUEST_TYPE -> "Tipo de requisição não autorizado"
            SpaySdk.ERROR_EXPIRED_OR_INVALID_DEBUG_KEY -> "Chave de debug expirada ou inválida"
            SpaySdk.ERROR_SERVER_INTERNAL -> "Erro interno do servidor"
            SpaySdk.ERROR_DEVICE_NOT_SAMSUNG -> "Dispositivo não é Samsung"
            SpaySdk.ERROR_SPAY_PKG_NOT_FOUND -> "Pacote Samsung Pay não encontrado"
            SpaySdk.ERROR_SPAY_SDK_SERVICE_NOT_AVAILABLE -> "Serviço SDK Samsung Pay não disponível"
            SpaySdk.ERROR_DEVICE_INTEGRITY_CHECK_FAIL -> "Falha na verificação de integridade do dispositivo"
            SpaySdk.ERROR_SPAY_APP_INTEGRITY_CHECK_FAIL -> "Falha na verificação de integridade do app Samsung Pay"
            SpaySdk.ERROR_ANDROID_PLATFORM_CHECK_FAIL -> "Falha na verificação da plataforma Android"
            SpaySdk.ERROR_MISSING_INFORMATION -> "Informações ausentes"
            SpaySdk.ERROR_SPAY_SETUP_NOT_COMPLETED -> "Configuração do Samsung Pay não concluída"
            SpaySdk.ERROR_SPAY_APP_NEED_TO_UPDATE -> "App Samsung Pay precisa ser atualizado"
            SpaySdk.ERROR_PARTNER_SDK_VERSION_NOT_ALLOWED -> "Versão do SDK parceiro não permitida"
            SpaySdk.ERROR_UNABLE_TO_VERIFY_CALLER -> "Não foi possível verificar o chamador"
            SpaySdk.ERROR_SPAY_FMM_LOCK -> "Samsung Pay bloqueado pelo FMM"
            SpaySdk.ERROR_SPAY_CONNECTED_WITH_EXTERNAL_DISPLAY -> "Samsung Pay conectado com display externo"
            SpaySdk.SPAY_NOT_SUPPORTED -> "Samsung Pay não suportado"
            SpaySdk.SPAY_NOT_READY -> "Samsung Pay não está pronto"
            SpaySdk.SPAY_READY -> "Samsung Pay está pronto"
            SpaySdk.SPAY_NOT_ALLOWED_TEMPORALLY -> "Samsung Pay não permitido temporariamente"
            SpaySdk.SPAY_HAS_TRANSIT_CARD -> "Samsung Pay tem cartão de trânsito"
            SpaySdk.SPAY_HAS_NO_TRANSIT_CARD -> "Samsung Pay não tem cartão de trânsito"
            else -> "Erro desconhecido: $errorCode"
        }
    }
}